### ISSUE TITLE
after upgrade to M4 I started to notice connection problems

### ISSUE THREAD

**Issue by modenet** [mvalla/openhab-addons#106]
after some days after reboot I notice that commands sent to alexa are no longer executed

these are the errors on log:

2020-06-28 17:04:37.718 [ome.event.ItemCommandEvent] - Item 'openwebnet_bus_on_off_switch_MH202_000350012774_33_switch' received command ON

2020-06-28 17:04:37.722 [nt.ItemStatePredictedEvent] - openwebnet_bus_on_off_switch_MH202_000350012774_33_switch predicted to become ON

or
2020-06-28 17:04:58.464 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

java.lang.OutOfMemoryError: unable to create new native thread

	at java.lang.Thread.start0(Native Method) ~[?:1.8.0_222]

	at java.lang.Thread.start(Thread.java:717) ~[?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957) ~[?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1603) ~[?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor.reExecutePeriodic(ScheduledThreadPoolExecutor.java:350) ~[?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:296) ~[?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

or
2020-06-28 17:05:06.676 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

java.lang.OutOfMemoryError: unable to create new native thread

	at java.lang.Thread.start0(Native Method) ~[?:1.8.0_222]

	at java.lang.Thread.start(Thread.java:717) ~[?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957) ~[?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1603) ~[?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor.reExecutePeriodic(ScheduledThreadPoolExecutor.java:350) ~[?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:296) ~[?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by modenet** [comment]
depending to Amazon bundle
